//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnalyticProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int AttachmentId { get; set; }
        public int ConversationId { get; set; }
        public string ContentType { get; set; }
        public string ContentUrl { get; set; }
        public Nullable<bool> isAdultContent { get; set; }
        public Nullable<bool> isRacyContent { get; set; }
        public Nullable<float> adultScore { get; set; }
        public Nullable<float> racyScore { get; set; }
    
        public virtual Conversation Conversation { get; set; }
    }
}
