//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnalyticProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public long Id { get; set; }
        public string Channel { get; set; }
        public string AccountID { get; set; }
        public string AccountName { get; set; }
        public string ClientNotificationUri { get; set; }
        public Nullable<float> Lon { get; set; }
        public Nullable<float> Lat { get; set; }
        public byte[] version { get; set; }
        public System.DateTimeOffset createdAt { get; set; }
        public System.DateTimeOffset updatedAt { get; set; }
        public bool deleted { get; set; }
    }
}
