//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnalyticProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourcesProvided
    {
        public long Id { get; set; }
        public Nullable<int> ConversationId { get; set; }
        public Nullable<long> ResourceId { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
