//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnalyticProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Conversations = new HashSet<Conversation>();
        }
    
        public int SessionId { get; set; }
        public string ChannelId { get; set; }
        public System.DateTime UtcDateTime { get; set; }
    
        public virtual ICollection<Conversation> Conversations { get; set; }
    }
}
