//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityPlusBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public Conversation()
        {
            this.Attachments = new HashSet<Attachment>();
        }
    
        public int ConversationId { get; set; }
        public int SessionId { get; set; }
        public string Text { get; set; }
        public string Locale { get; set; }
        public string Address { get; set; }
        public System.Data.Spatial.DbGeography GeoCoordinates { get; set; }
        public System.DateTime UtcDateTime { get; set; }
        public Nullable<float> sentiment { get; set; }
    
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual Session Session { get; set; }
    }
}
